### PR TITLE
Fix rebar.config

### PR DESCRIPTION
**Pull request by vkatsuba**
Related to issue https://github.com/rabbitmq/looking_glass/issues/12

### CODE REVIEW

**Comment by lhoguin** [comment]
Did you make it work with rebar3 when looking_glass is a top-level project, or when looking_glass is a dependency, or both?

**Comment by vkatsuba** [comment]
> Did you make it work with rebar3 when looking_glass is a top-level project, or when looking_glass is a dependency, or both?

Was checked both, plus in separate commit was provided GitHub Actions for run common tests, checked version of OTP `22.3.4.16, 23.0.4, 23.1.5.0, 23.2.7.0`, if needed I can add more.

**Comment by vkatsuba** [comment]
Result of CT
* `rebar3 ct` https://github.com/vkatsuba/looking_glass/runs/2352736207
* `rebar3 ct` + `make ct` https://github.com/vkatsuba/looking_glass/runs/2352816181

**Comment by lhoguin** [comment]
We are not using rebar3 for development so it is the dependency case that we are most interested in. We will need to double check that it works when used as a rebar3 dependency when reviewing the PR, as well as make sure it does not break non-rebar3 usage. Thanks for your contribution!

**Comment by michaelklishin** [comment]
@lhoguin do we still want to adopt this?

**Comment by lhoguin** [comment]
We only need the deps line. I have cherry-picked that part. Thanks!

**Pull request closed without merging**
